### ISSUE TITLE
Gray placeholder label for mdl-select

### ISSUE THREAD

**Issue by micdalco** [mseemann/angular2-mdl-ext#116]
I'd like to have gray colored text label for placeholder of mdl-select, coherently to other mdl fields.

See the plnkr:
http://plnkr.co/edit/3GHZHgxOGhDdrfAQHlv2?p=preview

![schermata 2016-11-23 alle 12 44 08](https://cloud.githubusercontent.com/assets/1583334/20570636/b63dafd2-b1a4-11e6-9122-6822091d1362.png)

**Comment by mseemann** [comment]
http://stackoverflow.com/questions/40763779/how-to-have-angular2-mdl-ext-select-placeholder-grayed-out

**Comment by ctdocken** [comment]
You should be able to replace the <div> in select.html with a readonly input to address this issue:

  <input readonly tabindex="-1"
      [placeholder]="placeholder"
      class="mdl-textfield__input"
      (click)="toggle($event)"
      [attr.id]="textfieldId"
      [value]="text">

I have a fix in my fork, but it's not ready for a PR since I'm trying to add float labels (with animations) in the process: https://github.com/ctdocken/angular2-mdl-ext/blob/master/src/components/select/select.html

**Comment by mseemann** [comment]
published in version 0.6.0
