### ISSUE TITLE
Theming is not working for select in e2e-app

### ISSUE THREAD

**Issue by tb** [mseemann/angular2-mdl-ext#17]
Theming customization are not applied. You can see it by looking at the active selection text color - its not $palette-blue-500;.

We need to fix it in e2e-app and document how to apply customization.

This requires manual import of SCSS per component?

**Comment by mseemann** [comment]
this was the open issue. i need to think about how we can achieve customization for each component. this will need a little bit - just working on the mdl-dialog component...

**Comment by mseemann** [comment]
the problem is, that the style.scss is injected by webpack into the index.html file. after that angular take the styles from each component and created <style> elements in the head-element. we can do what we want the component css will allways override everything what is defined in our style.scss file.

what do you think about this solution: 
- we remove every style from the components - e.g. styleUrls[] is always empty.
- the user of the components need to create a style.scss for his app and must import the styles from each component he wants to use:

@import "color-definitions";

$color-primary: $palette-blue-500;
$color-primary-dark: $palette-blue-700;
$color-accent: $palette-amber-A200;
$color-primary-contrast: $color-dark-contrast;
$color-accent-contrast: $color-dark-contrast;

@import 'material-design-lite';
@import "../../components/select/select";
// or node_module/@angular2-mdl-ext/select/select


// he can also make the folder available for webpack
sassLoader: {
	includePaths: [util.root('node_modules', '@angular2-mdl'-ext, 'select')]
}

**Comment by tb** [comment]
I think removing ext styles from component styleUrls and loading them via app styles.scss is good. The regular angular2-mdl components dont have styleUrls either.

**Comment by mseemann** [comment]
ok, i change the code, add the docu for the users and publish the components.

**Comment by mseemann** [comment]
deployed and ublished
