### ISSUE TITLE
Renderer.animate is no longer supported!

### ISSUE THREAD

**Issue by PavlaQ** [mseemann/angular2-mdl-ext#643]
hi!

When you try use dalogServiceAlert angular says:

`ERROR Error: Renderer.animate is no longer supported!
    at RendererAdapter.animate (core.es5.js:10470) [angular]
    at MdlDialogHostComponent.show (mdl-dialog-host.component.js:79) [angular]
    at vendor.bundle.js:29645:39 [angular]
    at Object.onInvokeTask (core.es5.js:4116) [angular]
    at ZoneDelegate.invokeTask (zone.js:397) [angular]
    at Zone.runTask (zone.js:165) [<root> => angular]
    at ZoneTask.invoke (zone.js:460) [<root>]
    at timer (zone.js:1540) [<root>]`

**Comment by mseemann** [comment]
version of angular?, version of angular-mdl(-ext)? maybe wrong project because this package did not provide dalogServiceAlert .

**Comment by PavlaQ** [comment]
"@angular/core": "^4.0.2",
    "@angular2-mdl-ext/popover": "^0.6.0",
    "angular2-mdl": "^2.13.2",

**Comment by mseemann** [comment]
- the right git hub project for your problem is https://github.com/mseemann/angular2-mdl (because the dialogservice is part of that package).
- angular2-mdl has the following  "peerDependencies": {
    "@angular/core": "^2.0.2",
    "@angular/common": "^2.0.2",
    "@angular/forms": "^2.0.2"
} e.g. the angular version could not be greater than 2. so you should get a lot of warnings because of unmet peerdependencies from npm. did you igrnore them?
- as you can see at https://github.com/mseemann/angular2-mdl in the Readme.md you need to install @angular-mdl/core to be compatible with angular 4.

**Comment by PavlaQ** [comment]
It's working, thank you very much :) 👍
