### ISSUE TITLE
package.json moment dependency error

### ISSUE THREAD

**Issue by dudochkin-victor** [mseemann/angular2-mdl-ext#787]
Please fix the package.json for datepicker to correct moment package dependency and update npm pkg
was
"moment" : "^2.18.1"

should be 
"moment" : "2.18.1"

**Comment by mseemann** [comment]
why should this be wrong?

**Comment by dudochkin-victor** [comment]
Hi
I just get sources from
https://github.com/angularclass/angular2-webpack-starter

and added few lines:

    "@angular-mdl/core": "~4.0.3",
    "@angular-mdl/datepicker": "~0.0.2",
    "@angular-mdl/expansion-panel": "~0.0.4",
    "@angular-mdl/popover": "~0.6.3",
    "@angular-mdl/select": "~0.10.4",


result on the screenshot.

node v6.9.4
npm v3.10.10

so after i remove ^ sign all works. :)))
Thnx.

2017-05-19 22:51 GMT+07:00 Michael Seemann <notifications@github.com>:

**Comment by mseemann** [comment]
screenshot?

**Comment by dudochkin-victor** [comment]
:)))
sorry. i replied using gmail
![console sccreenshot](https://cloud.githubusercontent.com/assets/905818/26256798/ae8183cc-3cf0-11e7-8322-1b04e4b00fac.png)

**Comment by mseemann** [comment]
what you get is a warning. because you have not installed moment.js. see the readme: https://github.com/mseemann/angular2-mdl-ext/tree/master/src/components/datepicker. i decided to make it a peerdependency because i absolutely do not want that moment is installed multiple times with different versions if you already have installed moment.

the second call of npm install is a real error. it seems you have specified version 0.0.3 for @angular-mdl/datepicker. but the last version is 0.0.2

so please change the version of the datepicker to 0.0.2 and run npm install --save moment.

**Comment by dudochkin-victor** [comment]
As u see on screenshot, i entered again npm install  with 0.0.3 version of datepicker to show u which versions of node and npm i use. Previous i started it with 0.0.2 and after i got error, i SPECIALLY checked that the moment was not installed (not located in node_modules folder).
Step-by-step:
1. git clone https://github.com/angularclass/angular2-webpack-starter.git
2. add 
    "@angular-mdl/core": "~4.0.3",
    "@angular-mdl/datepicker": "~0.0.2",
    "@angular-mdl/expansion-panel": "~0.0.4",
    "@angular-mdl/popover": "~0.6.3",
    "@angular-mdl/select": "~0.10.4",
with correct 0.0.2 version

AND I GOT ERROR. if u not trust me i can record screencast with the clean install )))

**Comment by dudochkin-victor** [comment]
its not for me. i just solved it. do it for others. pls. coz i like yor project. thnx for great job.
